# Generated by Django 5.1.5 on 2025-04-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="affectation",
            name="end",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
