# Generated by Django 5.1.5 on 2025-04-13 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_alter_affectation_end"),
    ]

    operations = [
        migrations.AlterField(
            model_name="affectation",
            name="collaborateur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="affectation_set",
                to="dashboard.collaborateur",
            ),
        ),
        migrations.AlterField(
            model_name="affectation",
            name="fonction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="affectation_set",
                to="dashboard.fonction",
            ),
        ),
        migrations.AlterField(
            model_name="affectation",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="affectation_set",
                to="dashboard.restaurant",
            ),
        ),
    ]
